services:
  nginx:
    container_name: club4devs_nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./chatwoot.nginx.conf:/etc/nginx/conf.d/chatwoot.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - app-network

  certbot:
    container_name: club4devs_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"
    #command: ["certonly", "--webroot", "--webroot-path=/var/www/certbot", "--email", "guii_1@hotmail.com", "--agree-tos", "--no-eff-email", "-d", "${DOMAIN}", "-d", "${WWW_DOMAIN}"]
    environment:
      - DOMAIN=${DOMAIN}
      - WWW_DOMAIN=${WWW_DOMAIN}
    image: chatwoot/chatwoot:latest # Ou uma tag específica, ex: v3.5.0
    container_name: chatwoot_web
    restart: always
    volumes:
      - chatwoot_data:/app/storage # Para armazenamento local de anexos, se ACTIVE_STORAGE_SERVICE=local
    networks:
      - app-network

volumes:
  certbot_conf:
  certbot_www:

networks:
  app-network:
    driver: bridge
